### ISSUE TITLE
Adding support for accounts in more countries

### ISSUE THREAD

**Issue by guyluz11** [i2Echo/mi_iot_token#4]
Adding support for accounts in more countries

Adding support for more languages

Currently we allow authentication with a set of incomplete languages

https://github.com/i2Echo/mi_iot_token/blob/b64c8dd54b3c9734795e59b9a9c049661ab89b13/lib/src/api.dart#L9

Let's add more to the list to cover most or all.

Supported mi country names can be found in the app under 

> Profile -> Settings -> Region

Then it needed to get converted to 2 letters, we can use one of the following sites:
https://www.iban.com/country-codes
https://www.nationsonline.org/oneworld/country_code_list.htm
https://www.datahub.io/core/country-list

**Comment by i2Echo** [comment]
Maybe we can ask for chatgpt easily. ^^

**Comment by guyluz11** [comment]
Didn't test the new version yet but I saw that you have implemented it 😄.
Thanks, will close this issue now.
