### ISSUE TITLE
Update HTTP version

### ISSUE THREAD

**Issue by guyluz11** [i2Echo/mi_iot_token#6]
Getting conflict with HTTP version, lets update it

> Because mi_iot_token 1.0.0 depends on http ^0.13.5 and no versions of mi_iot_token match >1.0.0 <2.0.0, mi_iot_token ^1.0.0 requires http ^0.13.5.

**Comment by i2Echo** [comment]
The http 1.0.0 requires sdk version 3.0.0 or higher, current version of mi_iot_token (1.1.0) now supports SDK version 3.0.0.
